using Aspire.Hosting;
using Aspire.Hosting.ApplicationModel;
using Aspire.Hosting.Testing;
using Xunit;

namespace CritterWatch.Samples.Testing;

/// <summary>
/// Shared xUnit fixture that boots a CritterWatch sample's Aspire AppHost end-to-end and hands back
/// an <see cref="HttpClient"/> aimed at the <c>critterwatch</c> resource. Generic over the AppHost
/// entry-point type so every sample solution reuses the same launch/wait machinery — a solution's
/// <c>Tests/</c> project just instantiates <c>CritterWatchAppHostFixture&lt;Projects.MyAppHost&gt;</c>
/// (the <c>Projects.*</c> marker types are generated by Aspire when a test project references the
/// AppHost project).
/// </summary>
/// <remarks>
/// These tests spin up <b>real Docker containers</b> via Aspire, so they require a running Docker
/// daemon. They are tagged with <see cref="DockerRequired"/> (see <see cref="DockerRequiredCollection"/>)
/// so CI/dev environments without Docker can filter them out:
/// <c>dotnet test --filter "Category!=DockerRequired"</c>.
/// </remarks>
/// <typeparam name="TAppHost">
/// The AppHost program type — pass the Aspire-generated <c>Projects.*AppHost</c> marker, e.g.
/// <c>CritterWatchAppHostFixture&lt;Projects.Fleet_RabbitMq_AppHost&gt;</c>.
/// </typeparam>
public class CritterWatchAppHostFixture<TAppHost> : IAsyncLifetime
    where TAppHost : class
{
    /// <summary>The Aspire resource name the CritterWatch console must register under in every sample AppHost.</summary>
    public const string CritterWatchResourceName = "critterwatch";

    /// <summary>Generous default ceiling for the resource to reach <c>Running</c> — first-run container pulls are slow.</summary>
    public static readonly TimeSpan StartupTimeout = TimeSpan.FromMinutes(5);

    private DistributedApplication? _app;

    /// <summary>The running distributed application. Valid only after <see cref="InitializeAsync"/> completes.</summary>
    public DistributedApplication App =>
        _app ?? throw new InvalidOperationException("The AppHost has not been started yet.");

    /// <summary>
    /// Boots the AppHost: <c>DistributedApplicationTestingBuilder.CreateAsync&lt;TAppHost&gt;()</c> →
    /// <c>BuildAsync()</c> → <c>StartAsync()</c>, then blocks until the <c>critterwatch</c> resource
    /// reports <see cref="KnownResourceStates.Running"/>.
    /// </summary>
    public async Task InitializeAsync()
    {
        var builder = await DistributedApplicationTestingBuilder.CreateAsync<TAppHost>();

        _app = await builder.BuildAsync();
        await _app.StartAsync();

        await _app.ResourceNotifications
            .WaitForResourceAsync(CritterWatchResourceName, KnownResourceStates.Running)
            .WaitAsync(StartupTimeout);
    }

    /// <summary>
    /// Creates a fresh <see cref="HttpClient"/> pointed at the <c>critterwatch</c> resource's endpoint.
    /// Each call returns a new client — dispose it (or wrap in <c>using</c>) at the call site.
    /// </summary>
    public HttpClient CreateCritterWatchClient() => App.CreateHttpClient(CritterWatchResourceName, "http");

    public async Task DisposeAsync()
    {
        if (_app is not null)
        {
            await _app.DisposeAsync();
        }
    }
}
